name: gsfilms_app
description: Cliente Flutter GSFilms
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.2
  http: ^1.1.0
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.0
  better_player: ^0.0.96
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
